// Generated by Wrangler on Wed Sep 11 2024 15:39:34 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	API_KEYS: KVNamespace;
	ENVIRONMENT: "dev";
	SENTRY_DSN: "";
	DB: D1Database;
}
